@echo off
chcp 65001 > nul
echo [LOOM] 正在启动全栈环境...
echo [1/2] 启动后端 (3001 端口)...
start "LOOM Backend" /d backend npm run start:dev
echo [2/2] 启动前端 (5173 端口)...
start "LOOM Frontend" /d frontend npm run dev
echo 成功！请检查新打开的两个黑色窗口。
pause
